import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
dimensions = { lines = 50, columns = 120 }
opacity = 0.8

[env]
TERM = "xterm-256color"

[font]
size = 8

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"
