import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
dimensions = { lines = 50, columns = 120 }
opacity = 0.98

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "CaskaydiaMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaMono Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaMono Nerd Font"
style = "Regular"
